spring:
  datasource:
    url: jdbc:mysql://geport.mysql.database.azure.com/geport_test
    username: "geport"
    password: "!!aA04180303a!!"
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://mysql-container:3306/geport
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #                show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #(하이버네이트 전용속성) 이 기능을 사용하면 한번에 IN 쿼리로 원하는 갯수만큼 가져올 수 있다
    open-in-view: false