
spring:
  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/test
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  profiles:
    group:
      "local": "local, jwt, oauth,db,swagger"
    active: local
#  config:
#    activate:
#      on-profile: "local"


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace #이러면 쿼리 파라미터 로그를 남길 수 있다